### PR TITLE
Merge pull request #1 from AdrianDC/cm-14.1

### PR DESCRIPTION
**Pull request by Nicklas373**
Sync from latest source

### CODE REVIEW

**Comment by Nicklas373** [comment]
sorry, it was my mistake to take source

**Comment by AdrianDC** [comment]
You should Fetch / Reset to my current HEAD,
then edit settings to leave only "Allow rebase merging" in the merge options.

Next time you merge, you won't introduce Merge commits & keep the same history
as long as both history don't have differences in history.

Also, if you are taking my 8960t CVEs to 8x27, I invite you to put them on Gerrit.
I can easily merge them to keep the kernel secure for the ROMs still building with it.

**Comment by Nicklas373** [comment]
Okay, i'll try to do that next time when fetching update from 8960. During nicki it's outdated with kernel security, so i'm try to found patch for security. I'm already try to contribute with gerrit, but always getting a problem when fetch project. Maybe because i'm not using Lineage as source ROM project, okay. Please invite me, at least i want to make nicki secure and updated again like before.

Thanks for your response, sir

**Comment by AdrianDC** [comment]
You can push from any local fork of the kernel (event not bound to the ROM repo) with :
`git push ssh://GerritUserName@review.lineageos.org:29418/LineageOS/android_kernel_sony_msm8x27 HEAD:refs/for/cm-14.1`

Prior to committing, you can verify that your project is completely synced with upstream (and does not have merge histories or deviating commits :
`git fetch origin cm-14.1; git rev-list --left-right --count HEAD...FETCH_HEAD;`
It should show 0 (your new changes) and 0 (missing upstream changes).

I invite you to check my android_development_shell_tools project to ease things :
http://adriandc.github.io/android_development_shell_tools/#documentation-android_gerritrc----standalone-import-ready
https://github.com/AdrianDC/android_development_shell_tools/blob/master/android_gerrit.rc#L157
http://adriandc.github.io/android_development_shell_tools/#documentation-android_git_statsrc

**Comment by Nicklas373** [comment]
Hana@Amakura-Hana:/media/Hana/50644BA7644B8EA2/Slimrom/kernel/sony/msm8x27$ git push ssh:nicklas373@review.lineageos.org:29418/LineageOS/android_kernel_sony_msm8x27 HEAD:refs/for/cm-14.1
ssh: Could not resolve hostname ssh: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Sorry sir, but i don't have any access or owner to access?

**Comment by AdrianDC** [comment]
Quite obviously you need to have an account on https://review.lineageos.org
Also... It's ssh://, not ssh: (Would be good to double check and read error outputs ;) )

**Comment by Nicklas373** [comment]
i'm sorry sir, i'm still new user for gerrit. but i'm already create account using Google Authorization, but still give error.

sign_and_send_pubkey: signing failed: agent refused operation
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

and this when i'm using gksudo

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by AdrianDC** [comment]
Well now it's a question of SSH keys.
Go in your Gerrit settings and check the SSH Public keys section.

**Comment by Nicklas373** [comment]
i'm already added ssh-rsa key, but status is still empty

**Comment by AdrianDC** [comment]
Sorry but I can't do personal help about adding SSH keys on Gerrit.
Please look into it, there's plenty of information about it on Internet.

**Comment by Nicklas373** [comment]
Okay, i'll try to find it. Thanks for your response sir

**Pull request closed without merging**
